<a href="https://colab.research.google.com/github/rubusarbaro/supplychain-forecast-FIME/blob/main/ComparativePlots.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive #Permite usar los archivos del usuario.
import pandas as pd # Librería que permite la manipulación y análisis de datos.
import plotly.graph_objects as go # Librería que permite la creación de gráficas interactivas.

In [3]:
drive.mount('/content/drive', force_remount=True) # Monta el disco de la nube del usuario. Si ya se encuentra montada, vuelve a hacerlo.
wd = "/content/drive/MyDrive/Forecast_FIME/PIA/"

Mounted at /content/drive

   Unnamed: 0    dato
0  1991-11-12  3.0735
1  1991-11-13  3.0712
2  1991-11-14  3.0718
3  1991-11-15  3.0684
4  1991-11-16  3.0684

In [38]:
df_original = pd.read_csv(wd + "df_USDMXN_20250330.csv")
df_original.rename(columns = {"Unnamed: 0": "fecha"}, inplace = True)
df_original.set_index("fecha", inplace = True)

df_arima = pd.read_csv(wd + "forecast_USDMXN_ARIMA.csv")
df_arima.rename(columns = {"Unnamed: 0": "fecha", "predicted_mean": "dato"}, inplace = True)
df_arima.set_index("fecha", inplace = True)

df_holtwinter_auto = pd.read_csv(wd + "forecast_USDMXN_HoltWinter_auto.csv")
df_holtwinter_auto.rename(columns = {"Unnamed: 0": "fecha", "0": "dato"}, inplace = True)
df_holtwinter_auto.set_index("fecha", inplace = True)

df_holtwinter_manual = pd.read_csv(wd + "forecast_USDMXN_HoltWinter_manual.csv")
df_holtwinter_manual.rename(columns = {"Unnamed: 0": "fecha", "0": "dato"}, inplace = True)
df_holtwinter_manual.set_index("fecha", inplace = True)

df_prophet = pd.read_csv(wd + "forecast_USDMXN_Prophet.csv")
df_prophet.rename(columns = {"ds": "fecha", "yhat": "dato"}, inplace = True)
df_prophet.set_index("fecha", inplace = True)

In [36]:
df_holtwinter_auto

                 dato
fecha
1991-11-12   3.049858
1991-11-13   3.055374
1991-11-14   3.076792
1991-11-15   3.082597
1991-11-16   3.093467
...               ...
2025-06-22  20.407401
2025-06-23  20.398026
2025-06-24  20.353077
2025-06-25  20.374322
2025-06-26  20.350177

[12281 rows x 1 columns]

In [40]:
fig = go.Figure()

## ARIMA
fig.add_trace(
    go.Scatter(
        x=df_arima.index,
        y=df_arima["dato"],
        name = "ARIMA",
          line = dict(color = "#ff7f0e", width = 3, dash = "dash")
    )
)

## Holt-Winter (auto)
fig.add_trace(
    go.Scatter(
        x=df_holtwinter_auto.index,
        y=df_holtwinter_auto["dato"],
        name = "Holt-Winter (auto)",
          line = dict(color = "#2ca02c", width = 3, dash = "dash")
    )
)

## Holt-Winter (manual)
fig.add_trace(
    go.Scatter(
        x=df_holtwinter_manual.index,
        y=df_holtwinter_manual["dato"],
        name = "Holt-Winter (manual)",
          line = dict(color = "#d62728", width = 3, dash = "dash")
    )
)

## Prophet
fig.add_trace(
    go.Scatter(
        x=df_prophet.index,
        y=df_prophet["dato"],
        name = "Prophet",
          line = dict(color = "#9467bd", width = 3, dash = "dash")
    )
)

## Original
fig.add_trace(
    go.Scatter(
        x=df_original.index,
        y=df_original["dato"],
        name = "Real",
          line = dict(color = "#1f77b4", width = 3, dash = "dash")
    )
)

fig.update_layout(title = "Tasa de cambio real vs. pronosticada (comparativa)", xaxis_title="Tiempo", yaxis_title="Tasa de cambio")

fig.show()